"""empty message

Revision ID: 69c120183052
Revises: e6e3bc727490
Create Date: 2024-12-04 23:08:19.851383

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69c120183052'
down_revision = 'e6e3bc727490'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('prueba')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('prueba', sa.VARCHAR(length=80), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
